/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2025-05-04 14:55:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.page;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("  <title>Herbal Tea Shop</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/Home.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <!-- Top Banner -->\r\n");
      out.write("  <div class=\"top-banner\">Free shipping on orders over Rs.1000 Use code: LINGTONSKIRANA</div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Navbar -->\r\n");
      out.write("  <header class=\"navbar\">\r\n");
      out.write("    <div class=\"navbar-container\">\r\n");
      out.write("      <div class=\"logo\"><img src=\"./Screenshot_2025-04-17_185040-removebg-preview.png\"></div>\r\n");
      out.write("      <nav class=\"nav-links\">\r\n");
      out.write("    	<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home.jsp\">Home</a>\r\n");
      out.write("		<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Product.jsp\">Shop</a>\r\n");
      out.write("		<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Registration.jsp\">Register</a>\r\n");
      out.write("		<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Aboutus.jsp\">About Us</a>\r\n");
      out.write("		<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Login.jsp\">Login/Signin</a>\r\n");
      out.write("\r\n");
      out.write("      </nav>\r\n");
      out.write("      <div class=\"search\">\r\n");
      out.write("        <input type=\"text\" placeholder=\"Search product\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("\r\n");
      out.write("  <!-- Content -->\r\n");
      out.write("  <main>\r\n");
      out.write("    <section class=\"hero\">\r\n");
      out.write("      <div class=\"text\">\r\n");
      out.write("        <h1>Fresh Groceries Delivered to You</h1>\r\n");
      out.write("        <p>Browse our curated categories of fresh produce, dairy, snacks, and more. Get fast delivery across Kathmandu!</p>\r\n");
      out.write("        <a href=\"./product.html\"><button>Start Shopping</button></a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"img-wrapper\">\r\n");
      out.write("        <img src=\"https://static.vecteezy.com/system/resources/previews/048/560/473/non_2x/shopping-cart-filled-with-grocery-items-and-vegetables-isolated-on-a-transparent-background-png.png\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("  \r\n");
      out.write("    <!-- Featured Products -->\r\n");
      out.write("    <section class=\"features\">\r\n");
      out.write("      <h2>Our categories</h2>\r\n");
      out.write("      <div class=\"product-grid\">\r\n");
      out.write("        <div class=\"product-card\">\r\n");
      out.write("          <img src=\"https://cdn-icons-png.flaticon.com/512/1046/1046784.png\" alt=\"Vegetables\">\r\n");
      out.write("          <h3>InstantFood and Drinks</h3>\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"product-card\">\r\n");
      out.write("          <img src=\"https://cdn-icons-png.flaticon.com/512/1046/1046786.png\" alt=\"Fruits\">\r\n");
      out.write("          <h3>Fruits and Veletables</h3>\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"product-card\">\r\n");
      out.write("          <img src=\"https://cdn-icons-png.flaticon.com/512/3075/3075977.png\" alt=\"Dairy\">\r\n");
      out.write("          <h3>Milk & Dairy</h3>\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"product-card\">\r\n");
      out.write("          <img src=\"https://cdn-icons-png.flaticon.com/512/3600/3600923.png\" alt=\"Snacks\">\r\n");
      out.write("          <h3>Kitchen utensils and accessories</h3>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"product-card\">\r\n");
      out.write("          <img src=\"https://cdn-icons-png.flaticon.com/512/3600/3600923.png\" alt=\"Snacks\">\r\n");
      out.write("          <h3>Extras</h3>\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("  </main>\r\n");
      out.write("\r\n");
      out.write("  <!-- Footer -->\r\n");
      out.write("  <footer class=\"footer\">\r\n");
      out.write("    <div class=\"footer-container\">\r\n");
      out.write("        <div> <div class=\"footer-logo\"><img style=\"width: 100px;\" src=\"./Screenshot_2025-04-17_185040-removebg-preview.png\"></div></div>\r\n");
      out.write("        <div class=\"footer-links\">\r\n");
      out.write("            <div><strong>Shop</strong><br>All Teas<br>Best Sellers</div>\r\n");
      out.write("            <div><strong>About</strong><br>Our Story<br>Contact Us</div>\r\n");
      out.write("            <div><strong>Help</strong><br>FAQs<br>Shipping Info</div>\r\n");
      out.write("          </div>\r\n");
      out.write("  \r\n");
      out.write("      <div class=\"footer-right\">\r\n");
      out.write("      <h3>sign in to the store</h3>\r\n");
      out.write("       \r\n");
      out.write("        <a href=\"./signin.html\"><button>Sign In</button></a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer-bottom\">\r\n");
      out.write("     \r\n");
      out.write("      <p style=\"text-align: center;\">&copy; 2025 Lington Store. All rights reserved.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
