/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2025-05-04 14:30:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.page;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1745225474792L));
    _jspx_dependants.put("jar:file:/C:/Users/dibas/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LingtonStore/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602853272000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<meta charset=\"UTF-8\" />\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("	<script src=\"https://kit.fontawesome.com/64d58efce2.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/Login.css\" />\r\n");
      out.write("	<title>Sign in & Sign up Form</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"forms-container\">\r\n");
      out.write("			<div class=\"signin-signup\">\r\n");
      out.write("				 <form action=\"signincontroller\" method=\"post\" class=\"sign-in-form\">\r\n");
      out.write("					<h2 class=\"title\">Sign in</h2>\r\n");
      out.write("					<div class=\"input-field\">\r\n");
      out.write("						<i class=\"fas fa-user\"></i>\r\n");
      out.write("						<input type=\"text\" name=\"username\" placeholder=\"Username\" />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"input-field\">\r\n");
      out.write("						<i class=\"fas fa-lock\"></i>\r\n");
      out.write("						<input type=\"password\" name=\"password\" placeholder=\"Password\" />\r\n");
      out.write("					</div>\r\n");
      out.write("					<button type=\"submit\" value=\"Login\" class=\"Loginbtn\">Login</button>\r\n");
      out.write("					\r\n");
      out.write("				</form> \r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				   <!--  String firstName = request.getParameter(\"FirstName\");  // Updated to match HTML field name\r\n");
      out.write("	        String lastName = request.getParameter(\"LastName\");    // Updated to match HTML field name\r\n");
      out.write("	        String username = request.getParameter(\"Username\");\r\n");
      out.write("	        String dob = request.getParameter(\"Birthday\");         // Changed to \"birthday\" as per HTML form field\r\n");
      out.write("	        String gender = request.getParameter(\"Gender\");\r\n");
      out.write("	        String email = request.getParameter(\"Email\");          // Updated to match HTML field name\r\n");
      out.write("	        String phoneNumber = request.getParameter(\"Phone\");    // Updated to match HTML field name\r\n");
      out.write("	        String password = request.getParameter(\"Password\"); -->\r\n");
      out.write("	        \r\n");
      out.write("				 <form action=\"signupcontroller\" method= \"post\" class=\"sign-up-form\">\r\n");
      out.write("					<h2 class=\"title\">Sign up</h2>\r\n");
      out.write("					<div class=\"input-field\">\r\n");
      out.write("						<i class=\"fas fa-user\"></i>\r\n");
      out.write("						<input type=\"text\" id=\"Username\" value=\"Username\" name=\"Username\" placeholder=\"Username\" />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"input-field\">\r\n");
      out.write("						<i class=\"fas fa-envelope\"></i>\r\n");
      out.write("						<input type=\"text\" id=\"FirstName\" name=\"FirstName\" value=\"FirstName\" placeholder=\"FirstName\" />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"input-field\">\r\n");
      out.write("						<i class=\"fas fa-envelope\"></i>\r\n");
      out.write("						<input type=\"text\" id=\"LastName\" name=\"LastName\" value=\"LastName\" placeholder=\"LastName\" />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"input-field\">\r\n");
      out.write("						<i class=\"fas fa-envelope\"></i>\r\n");
      out.write("						<input type=\"date\" id=\"Birthday\" name=\"dob\" value=\"Birthday\" placeholder=\"Birthday\" />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"input-field\">\r\n");
      out.write("						<i class=\"fas fa-envelope\"></i>\r\n");
      out.write("						<input type=\"text\" id=\"Gender\" name=\"Gender\" value=\"Gender\" placeholder=\"Gender\" />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"input-field\">\r\n");
      out.write("						<i class=\"fas fa-envelope\"></i>\r\n");
      out.write("						<input type=\"email\" id=\"Email\" name=\"Email\" value=\"Email\" placeholder=\"Email\" />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"input-field\">\r\n");
      out.write("						<i class=\"fas fa-envelope\"></i>\r\n");
      out.write("						<input type=\"text\" id=\"Phone\" name=\"Phone\" value=\"Phone\" placeholder=\"Phone\" />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"input-field\">\r\n");
      out.write("						<i class=\"fas fa-lock\"></i>\r\n");
      out.write("						<input type=\"password\" id=\"Password\"  name=\"Password\" placeholder=\"Password\" />\r\n");
      out.write("					</div>\r\n");
      out.write("					<button type=\"submit\" class=\"Signupbtn\" value=\"Sign up\" >Signup</button>\r\n");
      out.write("			\r\n");
      out.write("					\r\n");
      out.write("				</form> \r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"panels-container\">\r\n");
      out.write("			<div class=\"panel left-panel\">\r\n");
      out.write("				<div class=\"content\">\r\n");
      out.write("					<h3>New here ?</h3>\r\n");
      out.write("					<p>\r\n");
      out.write("						Sign up to know more!!\r\n");
      out.write("					</p>\r\n");
      out.write("					<button class=\"btn transparent\" id=\"sign-up-btn\">\r\n");
      out.write("						Sign up\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<img  src=\"https://i.ibb.co/6HXL6q1/Privacy-policy-rafiki.png\" class=\"image\" alt=\"\" />\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"panel right-panel\">\r\n");
      out.write("				<div class=\"content\">\r\n");
      out.write("					<h3>One of us ?</h3>\r\n");
      out.write("					<p>\r\n");
      out.write("						shopping spree!!\r\n");
      out.write("					</p>\r\n");
      out.write("					<button class=\"btn transparent\" id=\"sign-in-btn\">\r\n");
      out.write("						Sign in\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<img src=\"https://i.ibb.co/nP8H853/Mobile-login-rafiki.png\"  class=\"image\" alt=\"\" />\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("<script>\r\n");
      out.write("const sign_in_btn = document.querySelector(\"#sign-in-btn\");\r\n");
      out.write("const sign_up_btn = document.querySelector(\"#sign-up-btn\");\r\n");
      out.write("const container = document.querySelector(\".container\");\r\n");
      out.write("\r\n");
      out.write("sign_up_btn.addEventListener(\"click\", () => {\r\n");
      out.write("  container.classList.add(\"sign-up-mode\");\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("sign_in_btn.addEventListener(\"click\", () => {\r\n");
      out.write("  container.classList.remove(\"sign-up-mode\");\r\n");
      out.write("});</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/page/Login.jsp(34,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty error}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    <div style=\"color: red;\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
